import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "../ui/dashboard/sidebar/sidebar";
import Navbar from "../ui/dashboard/navbar/navbar";
import styles from '../dashboard/dashboard.module.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={styles.container}>
      <div className={styles.menu}>
        <Sidebar/>
      </div>
        <div className={styles.content}>
          <Navbar/>
          <div className={styles.children} style={{padding:"25px"}}>
           {children}
          </div>
        </div>
    </div>
  );
}
